Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/classschedule
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true